### ISSUE TITLE
Proxy not proxied

### ISSUE THREAD

**Issue by raissanorth** [tractorcow/silverstripe-proxy-db#2] opened 2018-03-13 23:04 UTC
Steps I have taken to have this occur:

I tried to update FullTextSearch by adding the sample configuration provided in the ReadMe. 
I added a new `ProxyDBExtension` class containing:

```<?php

namespace SilverStripe\FullTextSearch\Search\Extensions;

use SilverStripe\Core\Extension;
use TractorCow\ClassProxy\Generators\ProxyGenerator;
use SilverStripe\FullTextSearch\Search\Updaters\SearchUpdater;

class ProxyDBExtension extends Extension
{
    public function updateProxy(ProxyGenerator &$proxy)
    {
        $proxy = $proxy->addMethod('manipulate', function ($args, $next) {
            $manipulation = $args[0];
            SearchUpdater::handle_manipulation($manipulation);
            return $next(...$args);
        });
    }
}
```

In the CMS I added new content and tried to save and publish it.  This caused the following error:

```
[Emergency] Uncaught InvalidArgumentException: Method manipulate is not proxied

POST /ss4/admin/pages/edit/EditForm/1/
Line 48 in /usr/local/var/www/ss4/vendor/tractorcow/classproxy/src/Proxied/ProxiedBehaviour.php

Source

39      * @param string $method
40      * @param array $args
41      * @param callable $last
42      * @return mixed
43      */
44     public function invoke($method, $args, $last)
45     {
46         // Prevent unregistered methods being called
47         if (!isset($this->methods[$method])) {
48             throw new InvalidArgumentException("Method {$method} is not proxied");
49         }
50         $next = $last;
51         foreach (array_reverse($this->methods[$method]) as $callable) {
52             $callable = Closure::bind($callable, $this->owner);
53             $next = function (...$args) use ($callable, $next) {
54                 return $callable($args, $next);

Trace

TractorCow\ClassProxy\Proxied\ProxiedBehaviour->invoke(manipulate, Array, Closure) 
ClassCreator.php(49) : eval()'d code:11
MySQLDatabase_ac19722->manipulate(Array) 
.cache.CLC.MySQLDatabase_ac19722:9
AuditLoggerManipulateCapture_MySQLDatabase_ac19722->manipulate(Array) 
DB.php:493
SilverStripe\ORM\DB::manipulate(Array) 
DataObject.php:1465
SilverStripe\ORM\DataObject->writeManipulation(SiteTree, 2018-03-14 11:43:20, ) 
DataObject.php:1511
SilverStripe\ORM\DataObject->write() 
Versioned.php:938
SilverStripe\Versioned\Versioned->writeWithoutVersion() 
call_user_func_array(Array, Array) 
Extensible.php:144
SilverStripe\View\ViewableData->SilverStripe\Core\{closure}(Page, Array) 
CustomMethods.php:61
SilverStripe\View\ViewableData->__call(writeWithoutVersion, Array) 
CMSMain.php:1662
SilverStripe\CMS\Controllers\CMSMain->save(Array, SilverStripe\Forms\Form) 
CMSMain.php:1893
SilverStripe\CMS\Controllers\CMSMain->publish(Array, SilverStripe\Forms\Form, SilverStripe\Control\HTTPRequest, SilverStripe\Admin\LeftAndMainFormRequestHandler) 
FormRequestHandler.php:231
SilverStripe\Forms\FormRequestHandler->httpSubmission(SilverStripe\Control\HTTPRequest) 
RequestHandler.php:319
SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, httpSubmission) 
RequestHandler.php:201
SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) 
RequestHandler.php:225
SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) 
Controller.php:212
SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest) 
LeftAndMain.php:752
SilverStripe\Admin\LeftAndMain->handleRequest(SilverStripe\Control\HTTPRequest) 
AdminRootController.php:123
SilverStripe\Admin\AdminRootController->handleRequest(SilverStripe\Control\HTTPRequest) 
Director.php:361
SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
DetectLocaleMiddleware.php:74
TractorCow\Fluent\Middleware\DetectLocaleMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
InitStateMiddleware.php:54
TractorCow\Fluent\Middleware\InitStateMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
VersionedHTTPMiddleware.php:40
SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
InitStateMiddleware.php:44
SilverStripe\Subsites\Middleware\InitStateMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
BasicAuthMiddleware.php:68
SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
AuthenticationMiddleware.php:61
SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
AkismetMiddleware.php:22
SilverStripe\Akismet\Config\AkismetMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
CanonicalURLMiddleware.php:155
SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
FlushMiddleware.php:26
SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
RequestProcessor.php:66
SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
HybridSessionMiddleware.php:18
SilverStripe\HybridSessions\Control\HybridSessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
AllowedHostsMiddleware.php:60
SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
TrustedProxyMiddleware.php:176
SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
InitialisationMiddleware.php:53
CWP\Core\Control\InitialisationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
HTTPMiddlewareAware.php:65
SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) 
Director.php:370
SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest) 
HTTPApplication.php:48
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
call_user_func(Closure, SilverStripe\Control\HTTPRequest) 
HTTPApplication.php:66
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
call_user_func(Closure, SilverStripe\Control\HTTPRequest) 
ErrorControlChainMiddleware.php:56
SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain) 
call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain) 
ErrorControlChain.php:236
SilverStripe\Core\Startup\ErrorControlChain->step() 
ErrorControlChain.php:226
SilverStripe\Core\Startup\ErrorControlChain->execute() 
ErrorControlChainMiddleware.php:69
SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) 
HTTPMiddlewareAware.php:62
SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) 
HTTPMiddlewareAware.php:65
SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) 
HTTPApplication.php:67
SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, ) 
HTTPApplication.php:49
SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest) 
index.php:17
```

**Comment by robbieaverill** [comment] 2018-03-14 03:58
So this is caused by (for me) the auditor module which is still proxying in the old style. Disabling that module means this works as expected.

**Comment by raissanorth** [comment] 2018-03-14 03:59
It appears that this issue was caused, because I had the [silverstripe-auditor] module (https://github.com/silverstripe/silverstripe-auditor) installed - after its removal it worked as expected and no errors were caused. At it's current stage, proxy-db can't be used with any other database proxy.

**Comment by robbieaverill** [comment] 2018-03-14 04:19
PR for auditor is at https://github.com/silverstripe/silverstripe-auditor/pull/18 which resolves this problem (not a problem with this module per-se)

**Comment by robbieaverill** [comment] 2018-06-12 05:06
Fixed with https://github.com/silverstripe/silverstripe-auditor/pull/18

**Closed by robbieaverill** 2018-06-12 05:06 UTC
